// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-my-hot-leads.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_hot_leads_default = defineTool({
  name: "list_my_hot_leads",
  title: "List my hot leads",
  description: "List the signed-in user's hot leads (P1 companies with lead_score >= 80). Returns up to 25 top-scoring companies assigned to or created by the user.",
  inputSchema: {
    limit: z.number().int().min(1).max(25).optional().describe("Max results (default 10)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const cap = limit ?? 10;
    const { data, error } = await supabaseForUser(ctx).from("companies").select("id, company_name, lead_score, priority_tier, city, state, website").or(`assigned_to_sales_rep_id.eq.${userId},created_by.eq.${userId}`).gte("lead_score", 80).order("lead_score", { ascending: false }).limit(cap);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, companies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-companies.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_companies_default = defineTool2({
  name: "search_companies",
  title: "Search companies",
  description: "Search companies visible to the signed-in user by partial name match. Returns id, name, score, priority tier and location for up to 20 matches.",
  inputSchema: {
    query: z2.string().trim().min(1).max(100).describe("Partial company name"),
    limit: z2.number().int().min(1).max(20).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("companies").select("id, company_name, lead_score, priority_tier, city, state, website, industry").ilike("company_name", `%${query}%`).limit(limit ?? 15);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, companies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-overdue-meetings.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_overdue_meetings_default = defineTool3({
  name: "list_overdue_meetings",
  title: "List overdue meetings",
  description: "List meetings for the signed-in user that were scheduled in the past but have no completed_date set.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const now = (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = await supabaseForUser3(ctx).from("outreach_activities").select("id, scheduled_date, company_id, activity_type, outcome, notes").or(`assigned_to.eq.${userId},created_by.eq.${userId}`).eq("activity_type", "meeting").lt("scheduled_date", now).is("completed_date", null).order("scheduled_date", { ascending: true }).limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, meetings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-notifications.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_notifications_default = defineTool4({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "List the signed-in user's notifications. Set unread_only to filter.",
  inputSchema: {
    unread_only: z3.boolean().optional().describe("Only unread notifications (default true)"),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    let query = supabaseForUser4(ctx).from("notifications").select("id, type, title, message, read, created_at, link_url").eq("user_id", userId).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (unread_only !== false) query = query.eq("read", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-company.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_company_default = defineTool5({
  name: "get_company",
  title: "Get company details",
  description: "Fetch detailed information for a single company by id, including scoring, segment, and location fields the signed-in user can see.",
  inputSchema: { company_id: z4.string().uuid() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ company_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("companies").select(
      "id, company_name, website, industry, city, state, country, lead_score, priority_tier, segment, employee_count, annual_revenue, created_at, updated_at"
    ).eq("id", company_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found or not accessible." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { company: data }
    };
  }
});

// src/lib/mcp/tools/create-activity.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_activity_default = defineTool6({
  name: "create_activity",
  title: "Log an activity",
  description: "Log a new outreach activity (call, email, meeting, note) against a company for the signed-in user.",
  inputSchema: {
    company_id: z5.string().uuid(),
    activity_type: z5.enum(["call", "email", "meeting", "note", "task"]),
    notes: z5.string().min(1).max(4e3),
    scheduled_date: z5.string().datetime().optional().describe("ISO timestamp for scheduled/planned activity"),
    outcome: z5.string().max(200).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async ({ company_id, activity_type, notes, scheduled_date, outcome }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const { data, error } = await supabaseForUser6(ctx).from("outreach_activities").insert({
      company_id,
      activity_type,
      notes,
      scheduled_date: scheduled_date ?? null,
      outcome: outcome ?? null,
      created_by: userId,
      assigned_to: userId
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Activity logged: ${data.id}` }],
      structuredContent: { activity: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fjajupvwitxipzatmmss";
var mcp_default = defineMcp({
  name: "nest-pro-connector-mcp",
  title: "Nest Pro Connector",
  version: "0.1.0",
  instructions: "Tools for the Nest Pro Connector CRM. Read the signed-in user's hot leads, overdue meetings, notifications, and search companies. Log outreach activities against companies. All access respects the user's role and RLS policies.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_my_hot_leads_default,
    search_companies_default,
    list_overdue_meetings_default,
    list_my_notifications_default,
    get_company_default,
    create_activity_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
